sudo: required
os: linux
language: minimal
services:
  - docker
before_install:
  - docker build -t mtchavez/react-test -f client/Dockerfile.dev ./client
script:
  - sh -i ./login-to-docker.sh
  - docker run -e CI=true mtchavez/react-test npm run test -- --coverage
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
