sudo: required
services:
  - docker
before_install:
  - docker build -t mtchavez/react-test -f client/Dockerfile.dev ./client
script:
  - docker run -e CI=true mtchavez/react-test npm run test -- --coverage
after_success:
  - docker build -t mtchavez/multi-client ./client
  - docker build -t mtchavez/multi-server ./server
  - docker build -t mtchavez/multi-worker ./worker
  - docker build -t mtchavez/multi-nginx ./nginx
  - docker login --username mtchavez --password "${DOCKER_PASSWORD}"
  - docker push mtchavez/multi-client
  - docker push mtchavez/multi-server
  - docker push mtchavez/multi-worker
  - docker push mtchavez/multi-nginx
