version: "3.1"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres_password
      PGPORT: 5432
    links:
      - postgres
      - redis
    volumes:
      - /app/node_modules
      - ./server:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - postgres
      - redis
    volumes:
      - /app/node_modules
      - ./worker:/app
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    links:
      - client
      - api
    ports:
      - 3000:80
